#!/usr/bin/env python3
"""
Personalize the Atom Grants kickoff-call deck for a partner institution.

Copies Kickoff_Deck/Kickoff_Deck.html into its own <Slug>_Kickoff/ folder, swaps the
cover tokens, inlines the partner logo, and (optionally) fills slide 03's three
"why you chose Atom" reason cards from a JSON file.

Slide 03 is the ONLY content slide that changes per partner, and its three reasons must
come from the partner's own stated words (kickoff/partnership transcript). This script
will not invent them: pass --reasons, or leave the placeholders in and fill them by hand.

Example:
    python3 .claude/skills/kickoff-deck/personalize.py \
        --institution "VCU Health" \
        --logo ~/Downloads/vcu-health.png \
        --date "July 2026" \
        --reasons vcu-reasons.json

reasons.json format (exactly 3 entries):
    [
      {"title": "Building out research development",
       "body":  "You are standing up an RD function and ..."},
      ...
    ]
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TEMPLATE = REPO / "Kickoff_Deck" / "Kickoff_Deck.html"

# Wide wordmark logos (VCU Health, ~3.2:1) need a shorter height than tall crests
# (Georgia Southern, ~1.65:1) to carry the same visual weight next to the Atom wordmark.
LOGO_CSS_WIDE = ".partner-logo-img { height: clamp(52px, 4.6vw, 68px); width: auto; max-width: 300px; object-fit: contain; display: block; }"
LOGO_CSS_TALL = ".partner-logo-img { height: clamp(64px, 5.6vw, 88px); width: auto; max-width: 260px; object-fit: contain; display: block; }"
LOGO_CSS_RE = re.compile(r"\.partner-logo-img \{[^}]*\}")


def slugify(name: str) -> str:
    s = re.sub(r"[^\w\s-]", "", name).strip()
    return re.sub(r"[\s-]+", "_", s)


def logo_aspect(path: Path) -> float | None:
    """Width/height ratio, or None if we can't read it (e.g. SVG)."""
    try:
        from PIL import Image

        with Image.open(path) as im:
            return im.size[0] / im.size[1]
    except Exception:
        return None


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def load_reasons(path: Path) -> list[dict]:
    reasons = json.loads(path.read_text())
    if not isinstance(reasons, list) or len(reasons) != 3:
        sys.exit(f"error: {path} must be a JSON list of exactly 3 {{title, body}} objects")
    for r in reasons:
        if not r.get("title") or not r.get("body"):
            sys.exit(f"error: every reason needs a non-empty 'title' and 'body' ({path})")
        for field in ("title", "body"):
            if "—" in r[field] or "–" in r[field]:
                sys.exit(f"error: em/en dash in reason {field!r} — house style bans them")
    return reasons


def main() -> None:
    p = argparse.ArgumentParser(description="Personalize the Atom kickoff-call deck.")
    p.add_argument("--institution", required=True, help='e.g. "VCU Health"')
    p.add_argument("--logo", required=True, type=Path, help="Partner logo (PNG/SVG/JPG/WebP)")
    p.add_argument("--name", default="Tomer du Sautoy", help="Presenter name")
    p.add_argument("--title", default="CEO and Co-Founder", help="Presenter title")
    p.add_argument("--date", default=date.today().strftime("%B %Y"), help='e.g. "July 2026"')
    p.add_argument("--reasons", type=Path, help="JSON file with 3 {title, body} reasons for slide 03")
    p.add_argument("--out", type=Path, help="Output folder (default: <Slug>_Kickoff/)")
    p.add_argument("--no-pdf", action="store_true", help="Skip PDF export")
    args = p.parse_args()

    if not TEMPLATE.exists():
        sys.exit(f"error: template not found at {TEMPLATE}")
    if not args.logo.exists():
        sys.exit(f"error: logo not found at {args.logo}")

    reasons = load_reasons(args.reasons) if args.reasons else None

    slug = slugify(args.institution)
    out_dir = args.out or (REPO / f"{slug}_Kickoff")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "img").mkdir(exist_ok=True)

    logo_name = f"{slug.lower().replace('_', '-')}{args.logo.suffix.lower()}"
    shutil.copy2(args.logo, out_dir / "img" / logo_name)

    html = TEMPLATE.read_text()

    # --- header comment ----------------------------------------------------------
    # Rewrite the template's doc-comment FIRST, so the token substitutions below
    # don't rewrite the very lines that document those tokens.
    html = html.replace(
        "  Atom Grants | Kickoff Call Deck (TEMPLATE)\n",
        f"  Atom Grants | Kickoff Call Deck for {args.institution}\n"
        "  Generated by .claude/skills/kickoff-deck/personalize.py from Kickoff_Deck/Kickoff_Deck.html.\n"
        "  Only the cover tokens and slide 03 differ from the template.\n",
        1,
    )
    html = re.sub(
        r"  PERSONALIZE PER PARTNER.*?\n(?=  Everything else)",
        f"  PERSONALIZED FOR {args.institution.upper()}:\n"
        f"    Cover:    {args.institution} logo, {args.name} ({args.title}), {args.date}\n"
        "    Slide 03: three reasons in the partner's own framing, from the transcript.\n",
        html,
        count=1,
        flags=re.DOTALL,
    )

    # --- logo sizing: wide wordmark vs tall crest -------------------------------
    ratio = logo_aspect(args.logo)
    html = LOGO_CSS_RE.sub(LOGO_CSS_WIDE if (ratio or 0) > 2.5 else LOGO_CSS_TALL, html, count=1)

    # --- cover ------------------------------------------------------------------
    inst = esc(args.institution)
    html = html.replace(
        '<span class="partner-logo">[Partner logo]</span>',
        f'<img class="partner-logo-img" src="img/{logo_name}" alt="{inst}">',
    )
    html = html.replace("[Your name], [Title]", f"{esc(args.name)}, {esc(args.title)}")
    html = html.replace("[Month YYYY]", esc(args.date))
    html = html.replace("[Institution name]", inst)
    html = html.replace(
        "<title>Atom Grants: Kickoff Call</title>",
        f"<title>Atom Grants Kickoff Call: {inst}</title>",
    )

    # --- slide 03: the only content slide that changes ---------------------------
    if reasons:
        for i, r in enumerate(reasons, start=1):
            html = html.replace(f"<h3>[Reason {i} title]</h3>", f"<h3>{esc(r['title'])}</h3>")
            body_token = (
                f"<p>[Reason {i}: one or two sentences in the partner's own framing.]</p>"
            )
            html = html.replace(body_token, f"<p>{esc(r['body'])}</p>")

    out_html = out_dir / f"{slug}_Kickoff.html"
    out_html.write_text(html)
    try:
        shown = out_html.relative_to(REPO)
    except ValueError:  # --out pointed outside the repo
        shown = out_html
    print(f"HTML:  {shown}")
    print(f"Logo:  img/{logo_name}" + (f"  (aspect {ratio:.2f}:1)" if ratio else "  (vector)"))

    leftover = re.findall(r"\[Reason \d[^\]]*\]", html)
    if leftover:
        print(
            f"\n  NOTE: slide 03 still has {len(leftover)} placeholder(s). Fill the three\n"
            "  reason cards with the partner's OWN stated reasons from the transcript.\n"
            "  Do not invent them.",
            file=sys.stderr,
        )

    if not args.no_pdf:
        # This deck's print CSS paginates correctly, so html-to-pdf gives a vector
        # PDF with selectable text (verified). No screenshot-and-stitch needed.
        subprocess.run(
            [
                sys.executable,
                str(REPO / ".claude/skills/html-to-pdf/export.py"),
                str(out_html),
                "--size",
                "13.333x7.5",
            ],
            check=True,
        )


if __name__ == "__main__":
    main()
